export const countryFlags = {
    USD: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/120px-Flag_of_the_United_States.svg.png',
    JPY: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/120px-Flag_of_Japan.svg.png',
    VND: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/120px-Flag_of_Vietnam.svg.png',
    SGD: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/120px-Flag_of_Singapore.svg.png',
    RUB: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/120px-Flag_of_Russia.svg.png',
    THB: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/120px-Flag_of_Thailand.svg.png',
    KRW: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/120px-Flag_of_South_Korea.svg.png',
    INR: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/120px-Flag_of_India.svg.png',
    EUR: 'https://img.freepik.com/free-vector/illustration-european-union-flag_53876-27018.jpg?w=360',
    AUD: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/120px-Flag_of_Australia_%28converted%29.svg.png',
    HKD: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/120px-Flag_of_the_People%27s_Republic_of_China.svg.png',
    CNY: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/120px-Flag_of_the_People%27s_Republic_of_China.svg.png',
    CAD: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/120px-Flag_of_Canada_%28Pantone%29.svg.png',
}



export const currencyUnits = [
    { code: 'AED', currency: 'United Arab Emirates dirham' },
    { code: 'AFN', currency: 'Afghan afghani' },
    { code: 'ALL', currency: 'Albanian lek' },
    { code: 'AMD', currency: 'Armenian dram' },
    { code: 'AOA', currency: 'Angolan kwanza' },
    { code: 'ARS', currency: 'Argentine peso' },
    { code: 'AUD', currency: 'Australian dollar' },
    { code: 'AZN', currency: 'Azerbaijani manat' },
    { code: 'BAM', currency: 'Bosnia and Herzegovina convertible mark' },
    { code: 'BBD', currency: 'Barbadian dollar' },
    { code: 'BDT', currency: 'Bangladeshi taka' },
    { code: 'BGN', currency: 'Bulgarian lev' },
    { code: 'BHD', currency: 'Bahraini dinar' },
    { code: 'BIF', currency: 'Burundian franc' },
    { code: 'BND', currency: 'Brunei dollar' },
    { code: 'BOB', currency: 'Bolivian boliviano' },
    { code: 'BRL', currency: 'Brazilian real' },
    { code: 'BSD', currency: 'Bahamian dollar' },
    { code: 'BTN', currency: 'Bhutanese ngultrum' },
    { code: 'BWP', currency: 'Botswana pula' },
    { code: 'BYN', currency: 'Belarusian ruble' },
    { code: 'BZD', currency: 'Belize dollar' },
    { code: 'CAD', currency: 'Canadian dollar' },
    { code: 'CDF', currency: 'Congolese franc' },
    { code: 'CHF', currency: 'Swiss franc' },
    { code: 'CLP', currency: 'Chilean peso' },
    { code: 'CNY', currency: 'Chinese yuan' },
    { code: 'COP', currency: 'Colombian peso' },
    { code: 'CRC', currency: 'Costa Rican colón' },
    { code: 'CUP', currency: 'Cuban peso' },
    { code: 'CVE', currency: 'Cape Verdean escudo' },
    { code: 'CZK', currency: 'Czech koruna' },
    { code: 'DJF', currency: 'Djiboutian franc' },
    { code: 'DKK', currency: 'Danish krone' },
    { code: 'DOP', currency: 'Dominican peso' },
    { code: 'DZD', currency: 'Algerian dinar' },
    { code: 'EGP', currency: 'Egyptian pound' },
    { code: 'ERN', currency: 'Eritrean nakfa' },
    { code: 'ETB', currency: 'Ethiopian birr' },
    { code: 'EUR', currency: 'Euro' },
    { code: 'FJD', currency: 'Fijian dollar' },
    { code: 'GBP', currency: 'British pound' },
    { code: 'GEL', currency: 'Georgian lari' },
    { code: 'GHS', currency: 'Ghanaian cedi' },
    { code: 'GMD', currency: 'Gambian dalasi' },
    { code: 'GNF', currency: 'Guinean franc' },
    { code: 'GTQ', currency: 'Guatemalan quetzal' },
    { code: 'GYD', currency: 'Guyanese dollar' },
    { code: 'HNL', currency: 'Honduran lempira' },
    { code: 'HRK', currency: 'Croatian kuna' },
    { code: 'HTG', currency: 'Haitian gourde' },
    { code: 'HUF', currency: 'Hungarian forint' },
    { code: 'IDR', currency: 'Indonesian rupiah' },
    { code: 'ILS', currency: 'Israeli new shekel' },
    { code: 'INR', currency: 'Indian rupee' },
    { code: 'IQD', currency: 'Iraqi dinar' },
    { code: 'IRR', currency: 'Iranian rial' },
    { code: 'ISK', currency: 'Icelandic króna' },
    { code: 'JMD', currency: 'Jamaican dollar' },
    { code: 'JOD', currency: 'Jordanian dinar' },
    { code: 'JPY', currency: 'Japanese yen' },
    { code: 'KES', currency: 'Kenyan shilling' },
    { code: 'KGS', currency: 'Kyrgyzstani som' },
    { code: 'KHR', currency: 'Cambodian riel' },
    { code: 'KMF', currency: 'Comorian franc' },
    { code: 'KPW', currency: 'North Korean won' },
    { code: 'KRW', currency: 'South Korean won' },
    { code: 'KWD', currency: 'Kuwaiti dinar' },
    { code: 'KZT', currency: 'Kazakhstani tenge' },
    { code: 'LAK', currency: 'Lao kip' },
    { code: 'LBP', currency: 'Lebanese pound' },
    { code: 'LKR', currency: 'Sri Lankan rupee' },
    { code: 'LRD', currency: 'Liberian dollar' },
    { code: 'LSL', currency: 'Lesotho loti' },
    { code: 'LYD', currency: 'Libyan dinar' },
    { code: 'MAD', currency: 'Moroccan dirham' },
    { code: 'MDL', currency: 'Moldovan leu' },
    { code: 'MGA', currency: 'Malagasy ariary' },
    { code: 'MKD', currency: 'Macedonian denar' },
    { code: 'MMK', currency: 'Burmese kyat' },
    { code: 'MNT', currency: 'Mongolian tögrög' },
    { code: 'MRO', currency: 'Mauritanian ouguiya' },
    { code: 'MUR', currency: 'Mauritian rupee' },
    { code: 'MVR', currency: 'Maldivian rufiyaa' },
    { code: 'MWK', currency: 'Malawian kwacha' },
    { code: 'MXN', currency: 'Mexican peso' },
    { code: 'MYR', currency: 'Malaysian ringgit' },
    { code: 'MZN', currency: 'Mozambican metical' },
    { code: 'NAD', currency: 'Namibian dollar' },
    { code: 'NGN', currency: 'Nigerian naira' },
    { code: 'NIO', currency: 'Nicaraguan córdoba' },
    { code: 'NOK', currency: 'Norwegian krone' },
    { code: 'NPR', currency: 'Nepalese rupee' },
    { code: 'NZD', currency: 'New Zealand dollar' },
    { code: 'OMR', currency: 'Omani rial' },
    { code: 'PAB', currency: 'Panamanian balboa' },
    { code: 'PEN', currency: 'Peruvian sol' },
    { code: 'PGK', currency: 'Papua New Guinean kina' },
    { code: 'PHP', currency: 'Philippine peso' },
    { code: 'PKR', currency: 'Pakistani rupee' },
    { code: 'PLN', currency: 'Polish zloty' },
    { code: 'PYG', currency: 'Paraguayan guaraní' },
    { code: 'QAR', currency: 'Qatari riyal' },
    { code: 'RON', currency: 'Romanian leu' },
    { code: 'RSD', currency: 'Serbian dinar' },
    { code: 'RUB', currency: 'Russian ruble' },
    { code: 'RWF', currency: 'Rwandan franc' },
    { code: 'SAR', currency: 'Saudi riyal' },
    { code: 'SBD', currency: 'Solomon Islands dollar' },
    { code: 'SCR', currency: 'Seychellois rupee' },
    { code: 'SDG', currency: 'Sudanese pound' },
    { code: 'SEK', currency: 'Swedish krona' },
    { code: 'SGD', currency: 'Singapore dollar' },
    { code: 'SLL', currency: 'Sierra Leonean leone' },
    { code: 'SOS', currency: 'Somali shilling' },
    { code: 'SRD', currency: 'Surinamese dollar' },
    { code: 'SSP', currency: 'South Sudanese pound' },
    { code: 'STD', currency: 'São Tomé and Príncipe dobra' },
    { code: 'SYP', currency: 'Syrian pound' },
    { code: 'SZL', currency: 'Swazi lilangeni' },
    { code: 'THB', currency: 'Thai baht' },
    { code: 'TJS', currency: 'Tajikistani somoni' },
    { code: 'TMT', currency: 'Turkmenistan manat' },
    { code: 'TND', currency: 'Tunisian dinar' },
    { code: 'TOP', currency: "Tongan pa'anga" },
    { code: 'TRY', currency: 'Turkish lira' },
    { code: 'TTD', currency: 'Trinidad and Tobago dollar' },
    { code: 'TWD', currency: 'New Taiwan dollar' },
    { code: 'TZS', currency: 'Tanzanian shilling' },
    { code: 'UAH', currency: 'Ukrainian hryvnia' },
    { code: 'UGX', currency: 'Ugandan shilling' },
    { code: 'USD', currency: 'United States dollar' },
    { code: 'UYU', currency: 'Uruguayan peso' },
    { code: 'UZS', currency: 'Uzbekistani som' },
    { code: 'VEF', currency: 'Venezuelan bolívar' },
    { code: 'VND', currency: 'Vietnamese dong' },
    { code: 'VUV', currency: 'Vanuatu vatu' },
    { code: 'WST', currency: 'Samoan tala' },
    { code: 'XAF', currency: 'Central African CFA franc' },
    { code: 'XCD', currency: 'East Caribbean dollar' },
    { code: 'XOF', currency: 'West African CFA franc' },
    { code: 'YER', currency: 'Yemeni rial' },
    { code: 'ZAR', currency: 'South African rand' },
    { code: 'ZMW', currency: 'Zambian kwacha' },
]