export const countryFlags = {
    USD: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/120px-Flag_of_the_United_States.svg.png',
    JPY: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/120px-Flag_of_Japan.svg.png',
    VND: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/120px-Flag_of_Vietnam.svg.png',
    SGD: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/120px-Flag_of_Singapore.svg.png',
    RUB: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/120px-Flag_of_Russia.svg.png',
    THB: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/120px-Flag_of_Thailand.svg.png',
    KRW: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/120px-Flag_of_South_Korea.svg.png',
    INR: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/120px-Flag_of_India.svg.png',
    EUR: 'https://img.freepik.com/free-vector/illustration-european-union-flag_53876-27018.jpg?w=360',
    AUD: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/120px-Flag_of_Australia_%28converted%29.svg.png',
    HKD: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/120px-Flag_of_the_People%27s_Republic_of_China.svg.png',
    CNY: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/120px-Flag_of_the_People%27s_Republic_of_China.svg.png',
    CAD: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/120px-Flag_of_Canada_%28Pantone%29.svg.png',
}

export const currencyUnits = [
    { code: 'AED', currency: 'United Arab Emirates dirham' },
    { code: 'AFN', currency: 'Afghan afghani' },
    { code: 'ALL', currency: 'Albanian lek' },
    { code: 'AMD', currency: 'Armenian dram' },
    { code: 'AOA', currency: 'Angolan kwanza' },
    { code: 'ARS', currency: 'Argentine peso' },
    { code: 'AUD', currency: 'Australian dollar' },
    { code: 'AZN', currency: 'Azerbaijani manat' },
    { code: 'BAM', currency: 'Bosnia and Herzegovina convertible mark' },
    { code: 'BBD', currency: 'Barbadian dollar' },
    { code: 'BDT', currency: 'Bangladeshi taka' },
    { code: 'BGN', currency: 'Bulgarian lev' },
    { code: 'BHD', currency: 'Bahraini dinar' },
    { code: 'BIF', currency: 'Burundian franc' },
    { code: 'BND', currency: 'Brunei dollar' },
    { code: 'BOB', currency: 'Bolivian boliviano' },
    { code: 'BRL', currency: 'Brazilian real' },
    { code: 'BSD', currency: 'Bahamian dollar' },
    { code: 'BTN', currency: 'Bhutanese ngultrum' },
    { code: 'BWP', currency: 'Botswana pula' },
    { code: 'BYN', currency: 'Belarusian ruble' },
    { code: 'BZD', currency: 'Belize dollar' },
    { code: 'CAD', currency: 'Canadian dollar' },
    { code: 'CDF', currency: 'Congolese franc' },
    { code: 'CHF', currency: 'Swiss franc' },
    { code: 'CLP', currency: 'Chilean peso' },
    { code: 'CNY', currency: 'Chinese yuan' },
    { code: 'COP', currency: 'Colombian peso' },
    { code: 'CRC', currency: 'Costa Rican colón' },
    { code: 'CUP', currency: 'Cuban peso' },
    { code: 'CVE', currency: 'Cape Verdean escudo' },
    { code: 'CZK', currency: 'Czech koruna' },
    { code: 'DJF', currency: 'Djiboutian franc' },
    { code: 'DKK', currency: 'Danish krone' },
    { code: 'DOP', currency: 'Dominican peso' },
    { code: 'DZD', currency: 'Algerian dinar' },
    { code: 'EGP', currency: 'Egyptian pound' },
    { code: 'ERN', currency: 'Eritrean nakfa' },
    { code: 'ETB', currency: 'Ethiopian birr' },
    { code: 'EUR', currency: 'Euro' },
    { code: 'FJD', currency: 'Fijian dollar' },
    { code: 'GBP', currency: 'British pound' },
    { code: 'GEL', currency: 'Georgian lari' },
    { code: 'GHS', currency: 'Ghanaian cedi' },
    { code: 'GMD', currency: 'Gambian dalasi' },
    { code: 'GNF', currency: 'Guinean franc' },
    { code: 'GTQ', currency: 'Guatemalan quetzal' },
    { code: 'GYD', currency: 'Guyanese dollar' },
    { code: 'HNL', currency: 'Honduran lempira' },
    { code: 'HRK', currency: 'Croatian kuna' },
    { code: 'HTG', currency: 'Haitian gourde' },
    { code: 'HUF', currency: 'Hungarian forint' },
    { code: 'IDR', currency: 'Indonesian rupiah' },
    { code: 'ILS', currency: 'Israeli new shekel' },
    { code: 'INR', currency: 'Indian rupee' },
    { code: 'IQD', currency: 'Iraqi dinar' },
    { code: 'IRR', currency: 'Iranian rial' },
    { code: 'ISK', currency: 'Icelandic króna' },
    { code: 'JMD', currency: 'Jamaican dollar' },
    { code: 'JOD', currency: 'Jordanian dinar' },
    { code: 'JPY', currency: 'Japanese yen' },
    { code: 'KES', currency: 'Kenyan shilling' },
    { code: 'KGS', currency: 'Kyrgyzstani som' },
    { code: 'KHR', currency: 'Cambodian riel' },
    { code: 'KMF', currency: 'Comorian franc' },
    { code: 'KPW', currency: 'North Korean won' },
    { code: 'KRW', currency: 'South Korean won' },
    { code: 'KWD', currency: 'Kuwaiti dinar' },
    { code: 'KZT', currency: 'Kazakhstani tenge' },
    { code: 'LAK', currency: 'Lao kip' },
    { code: 'LBP', currency: 'Lebanese pound' },
    { code: 'LKR', currency: 'Sri Lankan rupee' },
    { code: 'LRD', currency: 'Liberian dollar' },
    { code: 'LSL', currency: 'Lesotho loti' },
    { code: 'LYD', currency: 'Libyan dinar' },
    { code: 'MAD', currency: 'Moroccan dirham' },
    { code: 'MDL', currency: 'Moldovan leu' },
    { code: 'MGA', currency: 'Malagasy ariary' },
    { code: 'MKD', currency: 'Macedonian denar' },
    { code: 'MMK', currency: 'Burmese kyat' },
    { code: 'MNT', currency: 'Mongolian tögrög' },
    { code: 'MRO', currency: 'Mauritanian ouguiya' },
    { code: 'MUR', currency: 'Mauritian rupee' },
    { code: 'MVR', currency: 'Maldivian rufiyaa' },
    { code: 'MWK', currency: 'Malawian kwacha' },
    { code: 'MXN', currency: 'Mexican peso' },
    { code: 'MYR', currency: 'Malaysian ringgit' },
    { code: 'MZN', currency: 'Mozambican metical' },
    { code: 'NAD', currency: 'Namibian dollar' },
    { code: 'NGN', currency: 'Nigerian naira' },
    { code: 'NIO', currency: 'Nicaraguan córdoba' },
    { code: 'NOK', currency: 'Norwegian krone' },
    { code: 'NPR', currency: 'Nepalese rupee' },
    { code: 'NZD', currency: 'New Zealand dollar' },
    { code: 'OMR', currency: 'Omani rial' },
    { code: 'PAB', currency: 'Panamanian balboa' },
    { code: 'PEN', currency: 'Peruvian sol' },
    { code: 'PGK', currency: 'Papua New Guinean kina' },
    { code: 'PHP', currency: 'Philippine peso' },
    { code: 'PKR', currency: 'Pakistani rupee' },
    { code: 'PLN', currency: 'Polish zloty' },
    { code: 'PYG', currency: 'Paraguayan guaraní' },
    { code: 'QAR', currency: 'Qatari riyal' },
    { code: 'RON', currency: 'Romanian leu' },
    { code: 'RSD', currency: 'Serbian dinar' },
    { code: 'RUB', currency: 'Russian ruble' },
    { code: 'RWF', currency: 'Rwandan franc' },
    { code: 'SAR', currency: 'Saudi riyal' },
    { code: 'SBD', currency: 'Solomon Islands dollar' },
    { code: 'SCR', currency: 'Seychellois rupee' },
    { code: 'SDG', currency: 'Sudanese pound' },
    { code: 'SEK', currency: 'Swedish krona' },
    { code: 'SGD', currency: 'Singapore dollar' },
    { code: 'SLL', currency: 'Sierra Leonean leone' },
    { code: 'SOS', currency: 'Somali shilling' },
    { code: 'SRD', currency: 'Surinamese dollar' },
    { code: 'SSP', currency: 'South Sudanese pound' },
    { code: 'STD', currency: 'São Tomé and Príncipe dobra' },
    { code: 'SYP', currency: 'Syrian pound' },
    { code: 'SZL', currency: 'Swazi lilangeni' },
    { code: 'THB', currency: 'Thai baht' },
    { code: 'TJS', currency: 'Tajikistani somoni' },
    { code: 'TMT', currency: 'Turkmenistan manat' },
    { code: 'TND', currency: 'Tunisian dinar' },
    { code: 'TOP', currency: "Tongan pa'anga" },
    { code: 'TRY', currency: 'Turkish lira' },
    { code: 'TTD', currency: 'Trinidad and Tobago dollar' },
    { code: 'TWD', currency: 'New Taiwan dollar' },
    { code: 'TZS', currency: 'Tanzanian shilling' },
    { code: 'UAH', currency: 'Ukrainian hryvnia' },
    { code: 'UGX', currency: 'Ugandan shilling' },
    { code: 'USD', currency: 'United States dollar' },
    { code: 'UYU', currency: 'Uruguayan peso' },
    { code: 'UZS', currency: 'Uzbekistani som' },
    { code: 'VEF', currency: 'Venezuelan bolívar' },
    { code: 'VND', currency: 'Vietnamese dong' },
    { code: 'VUV', currency: 'Vanuatu vatu' },
    { code: 'WST', currency: 'Samoan tala' },
    { code: 'XAF', currency: 'Central African CFA franc' },
    { code: 'XCD', currency: 'East Caribbean dollar' },
    { code: 'XOF', currency: 'West African CFA franc' },
    { code: 'YER', currency: 'Yemeni rial' },
    { code: 'ZAR', currency: 'South African rand' },
    { code: 'ZMW', currency: 'Zambian kwacha' },
]

export const defaultCurrency = {
    USD: { code: "USD", name: "United States dollar", value: 0.000042 },
    EUR: { code: "EUR", name: "Euro", value: 0.00004 },
    AED: { code: "AED", name: "United Arab Emirates dirham", value: 0.000156 },
    AFN: { code: "AFN", name: "Afghan afghani", value: 0.003689 },
    ALL: { code: "ALL", name: "Albanian lek", value: 0.004552 },
    AMD: { code: "AMD", name: "Armenian dram", value: 0.016697 },
    AOA: { code: "AOA", name: "Angolan kwanza", value: 0.021364 },
    ARS: { code: "ARS", name: "Argentine peso", value: 0.007375 },
    AUD: { code: "AUD", name: "Australian dollar", value: 0.000063 },
    AZN: { code: "AZN", name: "Azerbaijani manat", value: 0.000072 },
    BAM: { code: "BAM", name: "Bosnia and Herzegovina convertible mark", value: 0.000078 },
    BBD: { code: "BBD", name: "Barbadian dollar", value: 0.000086 },
    BDT: { code: "BDT", name: "Bangladeshi taka", value: 0.004487 },
    BGN: { code: "BGN", name: "Bulgarian lev", value: 0.000078 },
    BHD: { code: "BHD", name: "Bahraini dinar", value: 0.000016 },
    BIF: { code: "BIF", name: "Burundian franc", value: 0.087428 },
    BND: { code: "BND", name: "Brunei dollar", value: 0.000057 },
    BOB: { code: "BOB", name: "Bolivian boliviano", value: 0.000293 },
    BRL: { code: "BRL", name: "Brazilian real", value: 0.000219 },
    BSD: { code: "BSD", name: "Bahamian dollar", value: 0.000042 },
    BTN: { code: "BTN", name: "Bhutanese ngultrum", value: 0.003511 },
    BWP: { code: "BWP", name: "Botswana pula", value: 0.000544 },
    BYN: { code: "BYN", name: "Belarusian ruble", value: 0.000107 },
    BZD: { code: "BZD", name: "Belize dollar", value: 0.000085 },
    CAD: { code: "CAD", name: "Canadian dollar", value: 0.000058 },
    CDF: { code: "CDF", name: "Congolese franc", value: 0.086284 },
    CHF: { code: "CHF", name: "Swiss franc", value: 0.00004 },
    CLP: { code: "CLP", name: "Chilean peso", value: 0.037227 },
    CNY: { code: "CNY", name: "Chinese yuan", value: 0.000296 },
    COP: { code: "COP", name: "Colombian peso", value: 0.200638 },
    CRC: { code: "CRC", name: "Costa Rican colón", value: 0.024671 },
    CUP: { code: "CUP", name: "Cuban peso", value: 0.001124 },
    CVE: { code: "CVE", name: "Cape Verdean escudo", value: 0.004419 },
    CZK: { code: "CZK", name: "Czech koruna", value: 0.000966 },
    DJF: { code: "DJF", name: "Djiboutian franc", value: 0.007535 },
    DKK: { code: "DKK", name: "Danish krone", value: 0.000297 },
    DOP: { code: "DOP", name: "Dominican peso", value: 0.002364 },
    DZD: { code: "DZD", name: "Algerian dinar", value: 0.005831 },
    EGP: { code: "EGP", name: "Egyptian pound", value: 0.001044 },
    ERN: { code: "ERN", name: "Eritrean nakfa", value: 0.000636 },
    ETB: { code: "ETB", name: "Ethiopian birr", value: 0.002274 },
    FJD: { code: "FJD", name: "Fijian dollar", value: 0.000095 },
    GBP: { code: "GBP", name: "British pound", value: 0.000035 },
    GEL: { code: "GEL", name: "Georgian lari", value: 0.000113 },
    GHS: { code: "GHS", name: "Ghanaian cedi", value: 0.000424 },
    GMD: { code: "GMD", name: "Gambian dalasi", value: 0.002627 },
    GNF: { code: "GNF", name: "Guinean franc", value: 0.372059 },
    GTQ: { code: "GTQ", name: "Guatemalan quetzal", value: 0.000333 },
    GYD: { code: "GYD", name: "Guyanese dollar", value: 0.00887 },
    HNL: { code: "HNL", name: "Honduran lempira", value: 0.001046 },
    HRK: { code: "HRK", name: "Croatian kuna", value: 0.000301 },
    HTG: { code: "HTG", name: "Haitian gourde", value: 0.006232 },
    HUF: { code: "HUF", name: "Hungarian forint", value: 0.015996 },
    IDR: { code: "IDR", name: "Indonesian rupiah", value: 0.660695 },
    ILS: { code: "ILS", name: "Israeli new shekel", value: 0.000148 },
    INR: { code: "INR", name: "Indian rupee", value: 0.003502 },
    IQD: { code: "IQD", name: "Iraqi dinar", value: 0.061925 },
    IRR: { code: "IRR", name: "Iranian rial", value: 1.768073 },
    ISK: { code: "ISK", name: "Icelandic króna", value: 0.006083 },
    JMD: { code: "JMD", name: "Jamaican dollar", value: 0.006462 },
    JOD: { code: "JOD", name: "Jordanian dinar", value: 0.00003 },
    JPY: { code: "JPY", name: "Japanese yen", value: 0.005629 },
    KES: { code: "KES", name: "Kenyan shilling", value: 0.00523 },
    KGS: { code: "KGS", name: "Kyrgyzstani som", value: 0.003633 },
    KHR: { code: "KHR", name: "Cambodian riel", value: 0.174475 },
    KMF: { code: "KMF", name: "Comorian franc", value: 0.019676 },
    KPW: { code: "KPW", name: "North Korean won", value: 0.038157 },
    KRW: { code: "KRW", name: "South Korean won", value: 0.054282 },
    KWD: { code: "KWD", name: "Kuwaiti dinar", value: 0.000013 },
    KZT: { code: "KZT", name: "Kazakhstani tenge", value: 0.019576 },
    LAK: { code: "LAK", name: "Lao kip", value: 0.735213 },
    LBP: { code: "LBP", name: "Lebanese pound", value: 0.064533 },
    LKR: { code: "LKR", name: "Sri Lankan rupee", value: 0.015495 },
    LRD: { code: "LRD", name: "Liberian dollar", value: 0.006549 },
    LSL: { code: "LSL", name: "Lesotho loti", value: 0.00072 },
    LYD: { code: "LYD", name: "Libyan dinar", value: 0.000204 },
    MAD: { code: "MAD", name: "Moroccan dirham", value: 0.000445 },
    MDL: { code: "MDL", name: "Moldovan leu", value: 0.000816 },
    MGA: { code: "MGA", name: "Malagasy ariary", value: 0.188891 },
    MKD: { code: "MKD", name: "Macedonian denar", value: 0.002458 },
    MMK: { code: "MMK", name: "Burmese kyat", value: 0.089028 },
    MNT: { code: "MNT", name: "Mongolian tögrög", value: 0.145819 },
    MRO: { code: "MRO", name: "Mauritanian ouguiya", value: 0.015137 },
    MUR: { code: "MUR", name: "Mauritian rupee", value: 0.001874 },
    MVR: { code: "MVR", name: "Maldivian rufiyaa", value: 0.000653 },
    MWK: { code: "MWK", name: "Malawian kwacha", value: 0.043439 },
    MXN: { code: "MXN", name: "Mexican peso", value: 0.000821 },
    MYR: { code: "MYR", name: "Malaysian ringgit", value: 0.000188 },
    MZN: { code: "MZN", name: "Mozambican metical", value: 0.002706 },
    NAD: { code: "NAD", name: "Namibian dollar", value: 0.00072 },
    NGN: { code: "NGN", name: "Nigerian naira", value: 0.018937 },
    NIO: { code: "NIO", name: "Nicaraguan córdoba", value: 0.001544 },
    NOK: { code: "NOK", name: "Norwegian krone", value: 0.000421 },
    NPR: { code: "NPR", name: "Nepalese rupee", value: 0.005618 },
    NZD: { code: "NZD", name: "New Zealand dollar", value: 0.000067 },
    OMR: { code: "OMR", name: "Omani rial", value: 0.000016 },
    PAB: { code: "PAB", name: "Panamanian balboa", value: 0.000042 },
    PEN: { code: "PEN", name: "Peruvian sol", value: 0.000161 },
    PGK: { code: "PGK", name: "Papua New Guinean kina", value: 0.000149 },
    PHP: { code: "PHP", name: "Philippine peso", value: 0.002342 },
    PKR: { code: "PKR", name: "Pakistani rupee", value: 0.009561 },
    PLN: { code: "PLN", name: "Polish zloty", value: 0.000185 },
    PYG: { code: "PYG", name: "Paraguayan guaraní", value: 0.309825 },
    QAR: { code: "QAR", name: "Qatari riyal", value: 0.000154 },
    RON: { code: "RON", name: "Romanian leu", value: 0.000196 },
    RSD: { code: "RSD", name: "Serbian dinar", value: 0.004686 },
    RUB: { code: "RUB", name: "Russian ruble", value: 0.002979 },
    RWF: { code: "RWF", name: "Rwandan franc", value: 0.045241 },
    SAR: { code: "SAR", name: "Saudi riyal", value: 0.000159 },
    SBD: { code: "SBD", name: "Solomon Islands dollar", value: 0.000349 },
    SCR: { code: "SCR", name: "Seychellois rupee", value: 0.000604 },
    SDG: { code: "SDG", name: "Sudanese pound", value: 0.024274 },
    SEK: { code: "SEK", name: "Swedish krona", value: 0.000447 },
    SGD: { code: "SGD", name: "Singapore dollar", value: 0.000057 },
    SLL: { code: "SLL", name: "Sierra Leonean leone", value: 0.799025 },
    SOS: { code: "SOS", name: "Somali shilling", value: 0.024104 },
    SRD: { code: "SRD", name: "Surinamese dollar", value: 0.001341 },
    SSP: { code: "SSP", name: "South Sudanese pound", value: undefined },
    STD: { code: "STD", name: "São Tomé and Príncipe dobra", value: 0.877591 },
    SYP: { code: "SYP", name: "Syrian pound", value: 0.106524 },
    SZL: { code: "SZL", name: "Swazi lilangeni", value: 0.00072 },
    THB: { code: "THB", name: "Thai baht", value: 0.001473 },
    TJS: { code: "TJS", name: "Tajikistani somoni", value: 0.000433 },
    TMT: { code: "TMT", name: "Turkmenistan manat", value: 0.000149 },
    TND: { code: "TND", name: "Tunisian dinar", value: 0.000133 },
    TOP: { code: "TOP", name: "Tongan pa'anga", value: 0.0001 },
    TRY: { code: "TRY", name: "Turkish lira", value: 0.000791 },
    TTD: { code: "TTD", name: "Trinidad and Tobago dollar", value: 0.000288 },
    TWD: { code: "TWD", name: "New Taiwan dollar", value: 0.001304 },
    TZS: { code: "TZS", name: "Tanzanian shilling", value: 0.098961 },
    UAH: { code: "UAH", name: "Ukrainian hryvnia", value: 0.001566 },
    UGX: { code: "UGX", name: "Ugandan shilling", value: 0.154295 },
    UYU: { code: "UYU", name: "Uruguayan peso", value: 0.001626 },
    UZS: { code: "UZS", name: "Uzbekistani som", value: 0.475938 },
    VEF: { code: "VEF", name: "Venezuelan bolívar", value: 69.59986 },
    VND: { code: "VND", name: "Vietnamese dong", value: 1 },
    VUV: { code: "VUV", name: "Vanuatu vatu", value: 0.005049 },
    WST: { code: "WST", name: "Samoan tala", value: 0.000116 },
    XAF: { code: "XAF", name: "Central African CFA franc", value: 0.026201 },
    XCD: { code: "XCD", name: "East Caribbean dollar", value: 0.000115 },
    XOF: { code: "XOF", name: "West African CFA franc", value: 0.026182 },
    YER: { code: "YER", name: "Yemeni rial", value: 0.010613 },
    ZAR: { code: "ZAR", name: "South African rand", value: 0.000721 },
    ZMW: { code: "ZMW", name: "Zambian kwacha", value: 0.000759 }
}

export const convertTypes = ['currency', 'length', 'weight', 'acreage', 'volume', 'time', 'force', 'energy', 'wattage', 'pressure', 'speed'];
export const convertRatio = {
    currency: { ...defaultCurrency },
    length: {
        km: { value: 1 / (100 * 100 * 1000), name: 'Kilometer', code: 'km' },
        m: { value: 1 / (100 * 100), name: 'Meter', code: 'm' },
        dm: { value: 1 / (10 * 100), name: 'Decimeter', code: 'dm' },
        cm: { value: 1 / 100, name: 'Centimeter', code: 'cm' },
        mm: { value: 1, name: 'Millimeter', code: 'mm' },
        in: { value: 1 / 25.4, name: 'Inch', code: 'in' },
        ft: { value: 1 / 304.8, name: 'Foot', code: 'ft' },
        mi: { value: 1 / 1609344, name: 'Mile', code: 'mi' },
        nmi: { value: 1 / 1852000, name: 'Nautical Mile', code: 'nmi' },
    },
    weight: {
        t: { value: 1 / (1000 * 1000), name: 'Ton', code: 't' },
        kg: { value: 1 / 1000, name: 'Kilogram', code: 'kg' },
        g: { value: 1, name: 'Gram', code: 'g' },
        mg: { value: 1000, name: 'Miligram', code: 'mg' },
        lbs: { value: 1 / 453.59237, name: 'Pound', code: 'lbs' },
    },
    acreage: {
        km_square: { value: 1 / 10000000000, name: 'Kilometer Squares', code: 'km²' },
        m_square: { value: 1 / 10000, name: 'Kilometer Squares', code: 'm²' },
        dm_square: { value: 1 / 100, name: 'Decimeter Squares', code: 'dm²' },
        cm_square: { value: 1, name: 'Centimeter Squares', code: 'cm²' },
        ha: { value: 1 / 100000000, name: 'Hecta', code: 'ha' },
        in_square: { value: 1 / 6.4516, name: 'Inch Squares', code: 'in²' },
        ft_square: { value: 1 / 929.0304, name: 'Foot Squares', code: 'ft²' },
        mi_square: { value: 1 / 25899881103.36, name: 'Mile Squares', code: 'mi²' },
        ac: { value: 1 / 40468564.224, name: 'Acre', code: 'ac' },
    },
    volume: {
        l: { value: 1, name: 'Liter', code: 'ℓ' },
        cubic_m: { value: 1 / 1000, name: 'Cubic Meter', code: 'm³' },
        cubic_ft: { value: 1 / 28.316864592, name: 'Cubic Foot', code: 'ft³' },
        gal: { value: 1 / 3.785411784, name: 'Gallon', code: 'gal' },
        cubic_cm: { value: 1000, name: 'Cubic centimeter', code: 'cm³' },
    },
    time: {
        ms: { value: 1, name: 'Millisecond', code: 'ms' },
        s: { value: 1 / 1000, name: 'Second', code: 's' },
        m: { value: 1 / (1000 * 60), name: 'Minute', code: 'm' },
        h: { value: 1 / (1000 * 60 * 60), name: 'Hour', code: 'h' },
        d: { value: 1 / (1000 * 60 * 60 * 24), name: 'Day', code: 'd' },
        w: { value: 1 / (1000 * 60 * 60 * 24 * 7), name: 'Week', code: 'w' },
        mn: { value: 1 / (1000 * 60 * 60 * 24 * 30), name: 'Month', code: 'mn' },
        y: { value: 1 / (1000 * 60 * 60 * 24 * 365), name: 'Year', code: 'y' },
    },
    force: {
        kn: { value: 1 / 1000, name: 'Kilonewton', code: 'kN' },
        n: { value: 1, name: 'Newton', code: 'N' },
        kgf: { value: 1 / 9.8066, name: 'Kilogram Force', code: 'kgf' },
        gf: { value: 101.97162129779282, name: 'Gram Force', code: 'gf' },
        lbf: { value: 1 / 4.44822162, name: 'Pound Force', code: 'lbf' },
    },
    energy: {
        n: { value: 1, name: 'Newton', code: 'N' },
        kn: { value: 1 / 1000, name: 'Kilonewton', code: 'kN' },
        kgf: { value: 1 / 9.8066, name: 'Kilogram Force', code: 'kgf' },
    }
}